In [5]:
import numpy as np
import pandas as pd

data = pd.read_csv('/Users/takonyabadza/Desktop/soccer-spi/spi_global_rankings.csv')
data.head()

,rank,prev_rank,name,league,off,def,spi
0,1,1,Bayern Munich,German Bundesliga,3.49,0.38,94.37
1,2,2,Manchester City,Barclays Premier League,2.95,0.34,92.00
2,3,4,Paris Saint-Germain,French Ligue 1,2.96,0.48,90.08
3,4,3,Barcelona,Spanish Primera Division,2.83,0.44,89.66
4,5,6,Liverpool,Barclays Premier League,2.83,0.50,88.69